// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.openwebsys.identity.domain;

import java.lang.String;

privileged aspect IdAddress_Roo_JavaBean {
    
    public String IdAddress.getAddress1() {
        return this.address1;
    }
    
    public void IdAddress.setAddress1(String address1) {
        this.address1 = address1;
    }
    
}
